import { ethers } from "ethers";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { contract } from "../contract";
import styles from "../styles/Home.module.css";
// import chai from "../chai.png";

export default function Home() {
  const [signer, setSigner] = useState();
  const [amount, setAmount] = useState("");

  useEffect(() => connectToMetamask, []);

  const connectToMetamask = async () => {
    try {
      const provider = new ethers.providers.Web3Provider(
        window.ethereum,
        "any"
      );
      await provider.send("eth_requestAccounts", []);
      const signer = provider.getSigner();
      setSigner(signer);
      console.log("Account:", await signer.getAddress());
    } catch (err) {
      console.error(err);
    }
  };

  const buyCoffee = async () => {
    try {
      const smartContract = new ethers.Contract(
        contract.address,
        contract.abi,
        signer
      );
      await smartContract.functions.buyCoffee({
        value: ethers.utils.parseEther(amount),
      });
    } catch (err) {
      console.error(err);
      alert("Error buying coffee!");
    }
  };

  const withdraw = async () => {
    try {
      const smartContract = new ethers.Contract(
        contract.address,
        contract.abi,
        signer
      );
      await smartContract.functions.withdraw();
    } catch (err) {
      console.error(err);
      alert("Error withdrawing coffee!");
    }
  };

  return (
    <div className="main-container">
      <div className={styles.container}>
        <Head>
          <title>Buy me a coffee</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {/* <div>
          <img src={chai} alt="chai" />
        </div> */}

        <div className="main-section">
          <div className="coff-heading">
            <div>Buy Me A <span className="chai-icons">Coffee☕</span></div>   
            <i>To serve the perfect cup that brightens lives & brings people together</i>
          </div>
          
          
          <div className="main-work">
            <input
              type="text"
               value={amount}
              onChange={(e) => setAmount(e.target.value)}
              placeholder=""
            />
            <div className="buttons">
              <button className="buy-coffee" onClick={buyCoffee}>Buy Coffee</button>
              <button className="buy-coffee" onClick={withdraw}>Withdraw</button>
            </div>
            
          </div>
        </div>
      </div>
    </div>
  );
}
